#!/usr/bin/env python
"""Create every role, database and extension declared in registry/projects.yaml (M3, D13-D16).

Idempotent. Roles are created if missing and always re-pointed at the known password
(local default = the role name; <ROLE>_PASSWORD overrides). Databases are created if
missing, owned by the cluster superuser (D16). Extensions are created inside each
database, so no project ever needs superuser for `CREATE EXTENSION`. The registry
loader refuses duplicate role or database names before anything runs (D15).

The SQL is rendered as one psql script (\\connect between databases, \\gexec for the
CREATE DATABASE, which cannot run inside a transaction) and applied with psql inside
the postgres container by default, or against --superuser-url with a local psql.
--dry-run prints the script instead.

Afterwards .db-urls.env holds one block per project with its URLs, host-side
(localhost:<port>), so no project ever hardcodes a database URL, and .dbgate.env holds
the DB UI's connection list (one per project database, as the superuser, fenced to that
database — D20/D22) which the compose `dbgate` service reads at start.

    uv run scripts/db_init.py [--dry-run] [--only P5,P6]
                              [--psql "docker compose exec -T postgres psql"]
                              [--superuser-url postgresql://nmp:nmp@localhost:5432/nmp]
                              [--target local|aws] [--env-out .db-urls.env]
                              [--dbgate-out .dbgate.env] [--dbgate-readonly]
"""

from __future__ import annotations

import argparse
import os
import shlex
import subprocess
import sys
from pathlib import Path
from urllib.parse import urlsplit

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _registry import (  # noqa: E402
    DB_URLS_ENV_PATH,
    DBGATE_ENV_PATH,
    SUPERUSER,
    Database,
    Project,
    Registry,
    load_registry,
)


def role_password(role: str, db: Database | None = None) -> str:
    """<ROLE>_PASSWORD wins (AWS: Secrets Manager); else the registry's local default for the
    role, if it declares one (grandfathered names, D15); else the role name."""
    default = db.passwords.get(role, role) if db is not None else role
    return os.environ.get(f"{role.upper()}_PASSWORD", default)


def superuser_password(reg: Registry) -> str:
    return os.environ.get("POSTGRES_PASSWORD", reg.postgres_superuser)


def quote_literal(s: str) -> str:
    return "'" + s.replace("'", "''") + "'"


def render_sql(reg: Registry, projects: list[Project], target: str = "local") -> str:
    """The psql script that makes the cluster match the registry. Pure; unit-tested."""
    out: list[str] = [
        "-- generated by scripts/db_init.py from registry/projects.yaml; idempotent",
        "\\set ON_ERROR_STOP on",
    ]
    for p in projects:
        db = p.database
        assert db is not None
        if target == "aws" and not db.aws:
            out.append(f"-- {p.id} {db.name}: aws=false, skipped for target aws (D19)")
            continue
        out.append(f"\n-- {p.id} · {p.name} · database {db.name}")
        for role in db.roles:
            pw = quote_literal(role_password(role, db))
            opts = " ".join(db.options.get(role, []))
            opts = f" {opts}" if opts else ""
            out.append(
                "DO $$ BEGIN\n"
                f"  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = {quote_literal(role)})"
                " THEN\n"
                f"    CREATE ROLE {role} LOGIN PASSWORD {pw} NOSUPERUSER{opts};\n"
                "  END IF;\n"
                "END $$;"
            )
            out.append(f"ALTER ROLE {role} WITH LOGIN PASSWORD {pw}{opts};")
            for key, value in db.settings.get(role, {}).items():
                out.append(f"ALTER ROLE {role} SET {key} = {quote_literal(value)};")
        out.append(
            f"SELECT 'CREATE DATABASE {db.name} OWNER {reg.postgres_superuser}'\n"
            "  WHERE NOT EXISTS (SELECT 1 FROM pg_database WHERE datname = "
            f"{quote_literal(db.name)})\\gexec"
        )
        if db.extensions:
            out.append(f"\\connect {db.name}")
            for ext in db.extensions:
                out.append(f"CREATE EXTENSION IF NOT EXISTS {ext};")
            out.append(f"\\connect {reg.postgres_db}")
    return "\n".join(out) + "\n"


def url_for(reg: Registry, db: Database, role: str, scheme: str, base_uri: str) -> str:
    """postgresql[+driver]://role:password@host:port/database from the platform base URI."""
    parts = urlsplit(base_uri)
    host = parts.hostname or "localhost"
    port = parts.port or 5432
    if role == SUPERUSER:
        user, pw = reg.postgres_superuser, superuser_password(reg)
    else:
        user, pw = role, role_password(role, db)
    return f"{scheme}://{user}:{pw}@{host}:{port}/{db.name}"


def render_env(reg: Registry, projects: list[Project], base_uri: str) -> str:
    lines = [
        "# generated by scripts/db_init.py — do not edit. One block per project; copy the block",
        "# you need into that project's .env (variable names repeat across blocks; do not source).",
        f"PLATFORM_POSTGRES_URI={base_uri}",
    ]
    for p in projects:
        db = p.database
        assert db is not None
        lines.append("")
        lines.append(f"# {p.id} {p.name} -> database {db.name}  (paste into {p.path}/.env)")
        for e in db.env:
            lines.append(f"{e.var}={url_for(reg, db, e.role, e.scheme, base_uri)}")
    return "\n".join(lines) + "\n"


def render_dbgate_env(
    reg: Registry, projects: list[Project], readonly: bool = False, host: str | None = None
) -> str:
    """The DB UI's connection list: one DbGate connection per project database, as the cluster
    superuser (D16/D22) and fenced to that one database. Rendered from the registry so nobody
    types a host or password into the UI; the compose service reads it at start (D20).
    Pure; unit-tested."""
    parts = urlsplit(reg.postgres_uri_compose)
    server = host or parts.hostname or "postgres"
    port = parts.port or 5432
    su, pw = reg.postgres_superuser, superuser_password(reg)
    names = [p.database.name for p in projects if p.database is not None]
    out = [
        "# generated by scripts/db_init.py from registry/projects.yaml — do not edit.",
        "# Read by the compose `dbgate` service at start; `make db-init` re-renders and reloads.",
        f"CONNECTIONS={','.join(names)}",
    ]
    for p in projects:
        db = p.database
        assert db is not None
        n = db.name
        out += [
            "",
            f"LABEL_{n}={p.id} {p.name} · {n}",
            f"ENGINE_{n}=postgres@dbgate-plugin-postgres",
            f"SERVER_{n}={server}",
            f"PORT_{n}={port}",
            f"USER_{n}={su}",
            f"PASSWORD_{n}={pw}",
            f"DATABASE_{n}={n}",
            f"ALLOWED_DATABASES_{n}={n}",
        ]
        if readonly:
            out.append(f"READONLY_{n}=1")
        if db.ui_separate_schemas:
            out.append(f"USE_SEPARATE_SCHEMAS_{n}=1")
    return "\n".join(out) + "\n"


def apply(sql: str, psql_cmd: list[str]) -> int:
    proc = subprocess.run(psql_cmd, input=sql, text=True, capture_output=True)
    if proc.returncode != 0:
        sys.stderr.write(proc.stdout)
        sys.stderr.write(proc.stderr)
    return proc.returncode


def main() -> int:
    ap = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    ap.add_argument("--dry-run", action="store_true", help="print the SQL, apply nothing")
    ap.add_argument("--only", default="", help="comma-separated project ids")
    ap.add_argument("--target", choices=["local", "aws"], default="local")
    ap.add_argument(
        "--psql",
        default="docker compose exec -T postgres psql",
        help="command that runs psql as the superuser (default: inside the compose container)",
    )
    ap.add_argument(
        "--superuser-url", default=None, help="use a local psql against this URL instead"
    )
    ap.add_argument(
        "--base-uri",
        default=None,
        help="host-side base URI for .db-urls.env (default: registry/env)",
    )
    ap.add_argument("--env-out", default=str(DB_URLS_ENV_PATH))
    ap.add_argument("--dbgate-out", default=str(DBGATE_ENV_PATH))
    ap.add_argument(
        "--dbgate-readonly",
        action="store_true",
        help="render the DB UI's connections read-only (default: read-write as the superuser, D22)",
    )
    args = ap.parse_args()

    reg = load_registry()
    only = {s.strip() for s in args.only.split(",") if s.strip()}
    projects = [p for p in reg.databases if not only or p.id in only]
    if not projects:
        print("no projects with a database block selected")
        return 1

    sql = render_sql(reg, projects, target=args.target)
    if args.dry_run:
        sys.stdout.write(sql)
        return 0

    if args.superuser_url:
        cmd = ["psql", "-v", "ON_ERROR_STOP=1", args.superuser_url]
    else:
        cmd = shlex.split(args.psql) + [
            "-v",
            "ON_ERROR_STOP=1",
            "-U",
            reg.postgres_superuser,
            "-d",
            reg.postgres_db,
        ]
    code = apply(sql, cmd)
    if code != 0:
        print(f"db-init failed (psql exit {code})")
        return code

    port = os.environ.get("POSTGRES_PORT")
    base = args.base_uri or (f"postgresql://localhost:{port}" if port else reg.postgres_uri)
    Path(args.env_out).write_text(render_env(reg, reg.databases, base))  # always every project
    Path(args.dbgate_out).write_text(
        render_dbgate_env(reg, reg.databases, readonly=args.dbgate_readonly)
    )

    print(f"central Postgres: {base} (superuser {reg.postgres_superuser})")
    for p in projects:
        db = p.database
        assert db is not None
        skipped = args.target == "aws" and not db.aws
        state = "skipped (aws: false)" if skipped else "ready"
        roles = ",".join(db.roles) or "-"
        exts = ",".join(db.extensions) or "-"
        print(f"  {p.id:<8} {p.name:<18} db={db.name:<8} roles={roles:<32} ext={exts:<16} {state}")
    print(f"wrote {args.env_out}")
    print(
        f"wrote {args.dbgate_out} ({len(reg.databases)} DB UI connections; restart dbgate to load)"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
