#!/usr/bin/env python3
"""house_ui.py — render and distribute the house UI (D25-D32).

The house UI is one file, `agent/house/house.css`, byte-identical in every
project. The only thing a project owns is its hue, declared in
registry/projects.yaml and rendered here into a one-line `project.css`:

    :root{ --hue:80; }   /* P5 data-qa-agent */

So a project's artifacts link two stylesheets and nothing else:

    <link rel="stylesheet" href="house.css">
    <link rel="stylesheet" href="project.css">

Subcommands:
    render   write project.css for each project that declares a hue (default: --out)
    install  copy house.css, fonts/ and project.css into each project's .lavish/
    check    report which installed copies differ from the canon
    table    print hue, generated stops and measured contrast per project

`install` writes into sibling repositories, so it refuses to touch a copy a
human has edited unless FORCE=1 is set -- the same guard as install-agent-context.
"""

from __future__ import annotations

import argparse
import filecmp
import re
import shutil
import sys
from dataclasses import dataclass
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from _oklch import accent_for, contrast  # noqa: E402
from _registry import ROOT, Project, Registry, load_registry  # noqa: E402

HOUSE_DIR = ROOT / "agent" / "house"
HOUSE_CSS = HOUSE_DIR / "house.css"
FONTS_DIR = HOUSE_DIR / "fonts"
PROJECT_CSS = "project.css"
VERSION = re.compile(r"nmp house UI\s+(v\d+)")

LIGHT_BG, LIGHT_PANEL = "#F7F6F2", "#FFFFFF"
DARK_BG, DARK_PANEL = "#121614", "#191E1B"


def house_version(css: str) -> str:
    m = VERSION.search(css)
    return m.group(1) if m else "unversioned"


def render_project_css(project: Project, version: str) -> str:
    """The whole of a project's own styling: one declaration (D28)."""
    assert project.ui is not None
    return (
        f"/* {project.id} {project.name} — house UI {version}.\n"
        f"   Generated by `make house-ui` from registry/projects.yaml; do not edit.\n"
        f"   Load after house.css. The hue is the only thing this project owns. */\n"
        f":root{{ --hue:{project.ui.hue}; }}\n"
    )


def artifact_dir(project: Project) -> Path:
    return project.path / ".lavish"


@dataclass(frozen=True)
class Row:
    """One project's generated accent, with the worst ratio it reaches anywhere."""

    id: str
    name: str
    hue: int
    light: str
    dark: str
    worst: float


def rows(reg: Registry) -> list[Row]:
    out: list[Row] = []
    for p in reg.themed:
        assert p.ui is not None
        light, dark = accent_for(p.ui.hue, "light"), accent_for(p.ui.hue, "dark")
        out.append(
            Row(
                id=p.id,
                name=p.name,
                hue=p.ui.hue,
                light=light,
                dark=dark,
                worst=min(
                    contrast(light, LIGHT_BG),
                    contrast(light, LIGHT_PANEL),
                    contrast(dark, DARK_BG),
                    contrast(dark, DARK_PANEL),
                ),
            )
        )
    return out


def cmd_table(reg: Registry) -> int:
    print(f"{'ID':9s}{'project':24s}{'hue':>4s}  {'light':9s}{'dark':9s}{'worst':>7s}")
    worst = 21.0
    for r in rows(reg):
        print(f"{r.id:9s}{r.name:24s}{r.hue:4d}  {r.light:9s}{r.dark:9s}{r.worst:6.2f}:1")
        worst = min(worst, r.worst)
    print(f"\nworst accent/surface ratio across the portfolio: {worst:.2f}:1 (AA needs 4.5)")
    return 0


def cmd_render(reg: Registry, out: Path | None) -> int:
    version = house_version(HOUSE_CSS.read_text())
    target = out or (HOUSE_DIR / "rendered")
    target.mkdir(parents=True, exist_ok=True)
    for p in reg.themed:
        (target / f"{p.id}.css").write_text(render_project_css(p, version))
    print(f"rendered {len(reg.themed)} project stylesheets into {target.relative_to(ROOT)}")
    return 0


def cmd_install(reg: Registry, force: bool, dry_run: bool) -> int:
    version = house_version(HOUSE_CSS.read_text())
    problems = 0
    for p in reg.themed:
        dest = artifact_dir(p)
        if not dest.parent.exists():
            print(f"  skip   {p.id:9s} {p.path.name}: not checked out")
            continue
        installed = dest / "house.css"
        if installed.exists() and not filecmp.cmp(HOUSE_CSS, installed, shallow=False):
            if not force:
                print(f"  DIFFERS {p.id:9s} {dest}: edited locally; re-run with FORCE=1")
                problems += 1
                continue
        if dry_run:
            print(f"  would install {p.id:9s} -> {dest}")
            continue
        dest.mkdir(parents=True, exist_ok=True)
        shutil.copy2(HOUSE_CSS, installed)
        shutil.copytree(FONTS_DIR, dest / "fonts", dirs_exist_ok=True)
        (dest / PROJECT_CSS).write_text(render_project_css(p, version))
        print(f"  installed {p.id:9s} {version} -> {dest}")
    return 1 if problems else 0


def cmd_check(reg: Registry) -> int:
    canon = HOUSE_CSS.read_text()
    version = house_version(canon)
    behind = 0
    print(f"canon: house UI {version}  ({HOUSE_CSS.relative_to(ROOT)})")
    for p in reg.themed:
        installed = artifact_dir(p) / "house.css"
        if not installed.exists():
            print(f"  absent  {p.id:9s} {p.name:24s} no copy installed")
            behind += 1
            continue
        got = installed.read_text()
        if got == canon:
            print(f"  current {p.id:9s} {p.name:24s} {house_version(got)}")
        else:
            print(f"  BEHIND  {p.id:9s} {p.name:24s} {house_version(got)} != {version}")
            behind += 1
    if behind:
        print(f"\n{behind} project(s) not on the canon; run: make install-house-ui")
    return 0  # reporting target: never fails a build on its own


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "command", choices=["render", "install", "check", "table"], nargs="?", default="table"
    )
    ap.add_argument("--out", type=Path, help="render: directory to write into")
    ap.add_argument("--force", action="store_true", help="install: overwrite an edited copy")
    ap.add_argument("--dry-run", action="store_true", help="install: say what would happen")
    args = ap.parse_args()
    reg = load_registry()
    if not reg.themed:
        print("no project declares ui.hue", file=sys.stderr)
        return 1
    if args.command == "table":
        return cmd_table(reg)
    if args.command == "render":
        return cmd_render(reg, args.out)
    if args.command == "install":
        return cmd_install(reg, args.force, args.dry_run)
    return cmd_check(reg)


if __name__ == "__main__":
    raise SystemExit(main())
