#!/usr/bin/env python
"""Create every experiment declared in registry/projects.yaml on the central MLflow server.

Idempotent: existing experiments are left alone (deleted ones are restored), and the
numeric ids that OTLP clients need (data-qa's x-mlflow-experiment-id header) are written
to .mlflow-ids.env so no project ever hardcodes an id.

    uv run scripts/mlflow_init.py [--uri http://localhost:5000] [--env-out .mlflow-ids.env]
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from _registry import IDS_ENV_PATH, load_registry, resolve_uri  # noqa: E402


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--uri", default=None, help="tracking URI (default: env or registry)")
    ap.add_argument("--env-out", default=str(IDS_ENV_PATH))
    args = ap.parse_args()

    reg = load_registry()
    uri = resolve_uri(args.uri, reg)

    from mlflow import MlflowClient

    client = MlflowClient(tracking_uri=uri)
    rows: list[tuple[str, str, str, str]] = []
    env_lines: list[str] = ["# generated by scripts/mlflow_init.py — do not edit; source this file"]
    env_lines.append(f"MLFLOW_TRACKING_URI={uri}")

    for p in reg.projects:
        if not p.on_platform:
            continue
        for name in p.experiments:
            exp = client.get_experiment_by_name(name)
            if exp is None:
                eid = client.create_experiment(
                    name, tags={"project": p.name, "managed_by": "nmp-central-ai"}
                )
                state = "created"
            else:
                eid = exp.experiment_id
                if exp.lifecycle_stage == "deleted":
                    client.restore_experiment(eid)
                    state = "restored"
                else:
                    state = "exists"
                tags = exp.tags or {}
                if tags.get("project") != p.name:
                    client.set_experiment_tag(eid, "project", p.name)
                    client.set_experiment_tag(eid, "managed_by", "nmp-central-ai")
            rows.append((p.id, p.name, name, f"{eid} ({state})"))
            for var, exp_name in p.env_ids.items():
                if exp_name == name:
                    env_lines.append(f"{var}={eid}")

    width = max(len(r[2]) for r in rows) if rows else 10
    print(f"central MLflow: {uri}")
    for pid, proj, name, info in rows:
        print(f"  {pid:<3} {proj:<22} {name:<{width}}  -> {info}")
    Path(args.env_out).write_text("\n".join(env_lines) + "\n")
    print(f"wrote {args.env_out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
